import { Project, TaskItem, ActivityItem, UserAvatar } from '@/types';

export const teamAvatars: UserAvatar[] = [
  { id: '1', name: 'Sarah Chen', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80', role: 'Product Lead & Designer', email: 'sarah@taskflow.app' },
  { id: '2', name: 'Alex Rivera', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80', role: 'Senior Frontend Engineer', email: 'alex@taskflow.app' },
  { id: '3', name: 'Jamie Taylor', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', role: 'Fullstack Developer', email: 'jamie@taskflow.app' },
  { id: '4', name: 'David Kim', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80', role: 'Marketing Strategist', email: 'david@taskflow.app' },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'Website redesign',
    description: 'Redesign our marketing website for better UX and performance.',
    dueDate: 'May 30, 2025',
    progress: 68,
    iconType: 'laptop',
    iconBgColor: 'bg-slate-100 text-slate-700',
    iconColor: '#475569',
    progressBarColor: 'bg-indigo-600',
    owners: [teamAvatars[0], teamAvatars[1]],
    extraOwnersCount: 1,
  },
  {
    id: 'proj-2',
    title: 'Mobile app launch',
    description: 'Launch our new mobile app on iOS and Android.',
    dueDate: 'Jun 15, 2025',
    progress: 42,
    iconType: 'smartphone',
    iconBgColor: 'bg-slate-100 text-slate-700',
    iconColor: '#475569',
    progressBarColor: 'bg-indigo-600',
    owners: [teamAvatars[2], teamAvatars[3]],
    extraOwnersCount: 2,
  },
  {
    id: 'proj-3',
    title: 'Q3 campaign',
    description: 'Plan and execute our Q3 marketing campaign.',
    dueDate: 'Jul 10, 2025',
    progress: 25,
    iconType: 'megaphone',
    iconBgColor: 'bg-slate-100 text-slate-700',
    iconColor: '#475569',
    progressBarColor: 'bg-indigo-600',
    owners: [teamAvatars[0], teamAvatars[1]],
    extraOwnersCount: 1,
  },
];

export const initialTasks: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Review homepage mockups',
    projectName: 'Website redesign',
    assignee: teamAvatars[0],
    dueDate: 'May 22',
    dueStatus: 'Tomorrow',
    isUrgent: true,
    completed: false,
    status: 'To Do',
    priority: 'Urgent',
    description: 'Compare stakeholder comments against the latest homepage designs.',
    tags: ['Design', 'Client Review'],
    estimatedHours: 4,
    attachments: [
      { id: 'att-1', name: 'homepage-mockups-v3.pdf', size: '3.4 MB', type: 'pdf' },
      { id: 'att-2', name: 'design-feedback.png', size: '1.2 MB', type: 'image' },
    ],
    checklist: [
      { id: 'chk-1', text: 'Review desktop layout specs', completed: true },
      { id: 'chk-2', text: 'Check color contrast & typography', completed: false },
    ],
  },
  {
    id: 'task-2',
    title: 'Implement contact form',
    projectName: 'Website redesign',
    assignee: teamAvatars[1],
    dueDate: 'May 23',
    dueStatus: '2 days',
    isUrgent: true,
    completed: false,
    status: 'In Progress',
    priority: 'High',
    description: 'Build and test the new contact form flow before design review.',
    tags: ['Development', 'Review'],
    estimatedHours: 6,
    attachments: [
      { id: 'att-3', name: 'form-validation-spec.pdf', size: '420 KB', type: 'pdf' },
    ],
  },
  {
    id: 'task-3',
    title: 'Finalize brand assets',
    projectName: 'Q3 campaign',
    assignee: teamAvatars[2],
    dueDate: 'May 24',
    dueStatus: '3 days',
    isUrgent: true,
    completed: false,
    status: 'To Do',
    priority: 'High',
    description: 'Prepare final logos, colors, and social templates for campaign work.',
    tags: ['Design', 'Marketing'],
    estimatedHours: 5,
    attachments: [
      { id: 'att-4', name: 'brand-kit-q3.zip', size: '18.5 MB', type: 'zip' },
    ],
  },
  {
    id: 'task-4',
    title: 'iOS build beta testing',
    projectName: 'Mobile app launch',
    assignee: teamAvatars[3],
    dueDate: 'May 26',
    dueStatus: '5 days',
    isUrgent: false,
    completed: false,
    status: 'In Progress',
    priority: 'Medium',
    description: 'Coordinate beta tester feedback and record any launch blockers.',
    tags: ['Operations', 'Review'],
    estimatedHours: 8,
    attachments: [
      { id: 'att-5', name: 'testflight-build-notes.pdf', size: '890 KB', type: 'pdf' },
    ],
  },
  {
    id: 'task-5',
    title: 'Write campaign copy',
    projectName: 'Q3 campaign',
    assignee: teamAvatars[1],
    dueDate: 'May 28',
    dueStatus: '7 days',
    isUrgent: false,
    completed: false,
    status: 'To Do',
    priority: 'Low',
    description: 'Draft short copy variants for email, landing page, and social posts.',
    tags: ['Marketing', 'Strategy'],
    estimatedHours: 3,
  },
  {
    id: 'task-6',
    title: 'Database schema migration',
    projectName: 'Mobile app launch',
    assignee: teamAvatars[2],
    dueDate: 'May 30',
    dueStatus: '9 days',
    isUrgent: false,
    completed: true,
    status: 'Done',
    priority: 'Medium',
    description: 'Validate migration scripts and prepare rollback notes.',
    tags: ['Development', 'Operations'],
  },
  {
    id: 'task-7',
    title: 'Setup Google Analytics 4',
    projectName: 'Website redesign',
    assignee: teamAvatars[0],
    dueDate: 'Jun 02',
    dueStatus: '12 days',
    isUrgent: false,
    completed: false,
    status: 'To Do',
    priority: 'Low',
    description: 'Confirm events, goals, and dashboard widgets for the redesign launch.',
    tags: ['Marketing', 'Strategy'],
    estimatedHours: 2,
  },
];

export const initialActivities: ActivityItem[] = [
  {
    id: 'act-1',
    actor: 'Alex',
    actorAvatar: teamAvatars[1].avatarUrl,
    actionText: 'completed "Design system updates"',
    targetText: 'Website redesign',
    projectName: 'Website redesign',
    timeAgo: '2 hours ago',
    badgeType: 'check',
  },
  {
    id: 'act-2',
    actor: 'Jamie',
    actorAvatar: teamAvatars[2].avatarUrl,
    actionText: 'commented on "Homepage layout v2"',
    targetText: 'Website redesign',
    projectName: 'Website redesign',
    timeAgo: '4 hours ago',
    badgeType: 'comment',
  },
  {
    id: 'act-3',
    actor: 'Priya',
    actorAvatar: teamAvatars[0].avatarUrl,
    actionText: 'uploaded "Campaign brief.pdf"',
    targetText: 'Q3 campaign',
    projectName: 'Q3 campaign',
    timeAgo: 'Yesterday',
    badgeType: 'file',
  },
  {
    id: 'act-4',
    actor: 'You',
    actorAvatar: teamAvatars[3].avatarUrl,
    actionText: 'created task "Review analytics setup"',
    targetText: 'Mobile app launch',
    projectName: 'Mobile app launch',
    timeAgo: 'Yesterday',
    badgeType: 'calendar',
  },
];
